# python-app.yml 

on: 

  push: 

    branches: [ review ] 

    paths:  

    - 'src/Eye_Controlled_Mouse.py'  
    - 'src/osk.py'   

jobs: 

  build: 

    runs-on: ubuntu-latest 

    steps: 

    - uses: actions/checkout@v2 
    - name: Set up Python 3.10 

      uses: actions/setup-python@v2 

      with: 

        python-version: 3.10

    - name: Install dependencies 
      run: | 

        python -m pip install --upgrade pip 

        pip install pytest opencv-python mediapipe pyautogui

    - name: Test with pytest 
      run: | 

        pytest test/pytest_osk.py 
        pytest test/pytest_ecm.py
